"""Add min_votes column to VotePhase

Revision ID: 393bdd75dbb2
Revises: c255ab5a790d
Create Date: 2025-07-30 10:11:27.188077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393bdd75dbb2'
down_revision = 'c255ab5a790d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_phase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_votes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_phase', schema=None) as batch_op:
        batch_op.drop_column('min_votes')

    # ### end Alembic commands ###
