"""reset schema with correct vote constraint

Revision ID: 8201066e3aca
Revises: b49ab27ae8e3
Create Date: 2025-09-10 20:28:47.996712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8201066e3aca'
down_revision = 'b49ab27ae8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_vote_unique_voter_phase'), type_='unique')
        batch_op.create_unique_constraint('uix_vote_unique', ['voter_id', 'candidate_id', 'phase_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint('uix_vote_unique', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uix_vote_unique_voter_phase'), ['voter_id', 'phase_id'])

    # ### end Alembic commands ###
