"""add operation_logs table

Revision ID: 9bd27a0c4874
Revises: 8201066e3aca
Create Date: 2025-09-10 22:38:38.494968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd27a0c4874'
down_revision = '8201066e3aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_vote')
    op.drop_table('setting')
    op.drop_table('staff')
    op.drop_table('admin')
    op.drop_table('candidate')
    op.drop_table('vote_phase')
    op.drop_table('vote')
    op.drop_table('user')
    op.drop_table('operation_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=255), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=512), nullable=False),
    sa.Column('is_signed_in', sa.BOOLEAN(), nullable=True),
    sa.Column('signed_in_time', sa.DATETIME(), nullable=True),
    sa.Column('candidate_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('voter_id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), nullable=False),
    sa.Column('phase_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['vote_phase.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_id', 'candidate_id', 'phase_id', name=op.f('uix_vote_unique'))
    )
    op.create_table('vote_phase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_open', sa.BOOLEAN(), nullable=True),
    sa.Column('max_votes', sa.INTEGER(), nullable=True),
    sa.Column('min_votes', sa.INTEGER(), nullable=True),
    sa.Column('promote_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('parent_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phase_id', sa.INTEGER(), nullable=True),
    sa.Column('has_voted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_signed_in', sa.BOOLEAN(), nullable=True),
    sa.Column('signed_in_time', sa.DATETIME(), nullable=True),
    sa.Column('is_promoted', sa.BOOLEAN(), nullable=True),
    sa.Column('is_winner', sa.BOOLEAN(), nullable=True),
    sa.Column('promote_type', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['vote_phase.id'], name=op.f('fk_candidate_phase')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('staff',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=512), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('staff_vote',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('staff_id', sa.INTEGER(), nullable=False),
    sa.Column('vote_result', sa.VARCHAR(length=10), nullable=False),
    sa.Column('reset_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
