"""init database

Revision ID: b5eea718a195
Revises: 
Create Date: 2025-07-25 15:26:11.162898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eea718a195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vote_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('max_votes', sa.Integer(), nullable=True),
    sa.Column('promote_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('parent_name', sa.String(length=50), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('has_voted', sa.Boolean(), nullable=True),
    sa.Column('is_signed_in', sa.Boolean(), nullable=True),
    sa.Column('signed_in_time', sa.DateTime(), nullable=True),
    sa.Column('is_promoted', sa.Boolean(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('promote_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['vote_phase.id'], name='fk_candidate_phase'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'phase_id', name='uq_username_phase')
    )
    op.create_table('staff_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('vote_result', sa.String(length=10), nullable=False),
    sa.Column('reset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['vote_phase.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voter_id', 'candidate_id', 'phase_id', name='uix_vote_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('staff_vote')
    op.drop_table('candidate')
    op.drop_table('vote_phase')
    op.drop_table('staff')
    op.drop_table('setting')
    op.drop_table('admin')
    # ### end Alembic commands ###
